name: ci
on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Lint (ruff + black --check)
        run: |
          ruff --version
          ruff .
          black --check .
      - name: Tests
        run: pytest -q
